// Sample NFL player data for visualization
// In a real application, this would be fetched from an API or database

// Helper function to determine if a player is "elite" (top performers)
const isElitePlayer = (rating) => {
  return rating > 90
}

// Generate sample player data
export const playerData = [
  // Wide Receivers (WR)
  {
    id: 1,
    name: "Justin Jefferson",
    team: "MIN",
    position: "WR",
    manSeparation: 0.42,
    zoneSeparation: 0.31,
    catchRate: 72.5,
    yardsPerRoute: 2.8,
    targetShare: 28.4,
    redZoneTargets: 18,
    overallRating: 94.2,
    isElite: true,
    note: "Elite separator against both man and zone coverage",
  },
  {
    id: 2,
    name: "Tyreek Hill",
    team: "MIA",
    position: "WR",
    manSeparation: 0.38,
    zoneSeparation: 0.22,
    catchRate: 68.7,
    yardsPerRoute: 3.2,
    targetShare: 31.5,
    redZoneTargets: 15,
    overallRating: 93.8,
    isElite: true,
    note: "Speed threat who excels against man coverage",
  },
  {
    id: 3,
    name: "CeeDee Lamb",
    team: "DAL",
    position: "WR",
    manSeparation: 0.35,
    zoneSeparation: 0.28,
    catchRate: 70.2,
    yardsPerRoute: 2.6,
    targetShare: 30.1,
    redZoneTargets: 22,
    overallRating: 92.5,
    isElite: true,
    note: "Well-rounded receiver with excellent route running",
  },
  {
    id: 4,
    name: "Ja'Marr Chase",
    team: "CIN",
    position: "WR",
    manSeparation: 0.33,
    zoneSeparation: 0.25,
    catchRate: 67.8,
    yardsPerRoute: 2.7,
    targetShare: 29.3,
    redZoneTargets: 20,
    overallRating: 91.9,
    isElite: true,
    note: "Physical receiver who wins contested catches",
  },
  {
    id: 5,
    name: "Davante Adams",
    team: "LV",
    position: "WR",
    manSeparation: 0.31,
    zoneSeparation: 0.18,
    catchRate: 65.4,
    yardsPerRoute: 2.3,
    targetShare: 27.8,
    redZoneTargets: 24,
    overallRating: 90.6,
    isElite: true,
    note: "Elite release technique against press coverage",
  },
  {
    id: 6,
    name: "Amon-Ra St. Brown",
    team: "DET",
    position: "WR",
    manSeparation: 0.29,
    zoneSeparation: 0.32,
    catchRate: 74.1,
    yardsPerRoute: 2.4,
    targetShare: 28.9,
    redZoneTargets: 19,
    overallRating: 90.2,
    isElite: true,
    note: "Slot specialist who excels against zone coverage",
  },
  {
    id: 7,
    name: "Stefon Diggs",
    team: "HOU",
    position: "WR",
    manSeparation: 0.27,
    zoneSeparation: 0.26,
    catchRate: 69.3,
    yardsPerRoute: 2.2,
    targetShare: 25.6,
    redZoneTargets: 17,
    overallRating: 88.7,
    isElite: false,
    note: "Precise route runner with good hands",
  },
  {
    id: 8,
    name: "A.J. Brown",
    team: "PHI",
    position: "WR",
    manSeparation: 0.3,
    zoneSeparation: 0.21,
    catchRate: 66.8,
    yardsPerRoute: 2.5,
    targetShare: 26.7,
    redZoneTargets: 16,
    overallRating: 89.4,
    isElite: true,
    note: "Physical receiver who excels after the catch",
  },
  {
    id: 9,
    name: "DeVonta Smith",
    team: "PHI",
    position: "WR",
    manSeparation: 0.28,
    zoneSeparation: 0.24,
    catchRate: 71.5,
    yardsPerRoute: 2.1,
    targetShare: 23.4,
    redZoneTargets: 14,
    overallRating: 87.9,
    isElite: false,
    note: "Smooth route runner with good body control",
  },
  {
    id: 10,
    name: "Keenan Allen",
    team: "CHI",
    position: "WR",
    manSeparation: 0.25,
    zoneSeparation: 0.3,
    catchRate: 73.2,
    yardsPerRoute: 2.0,
    targetShare: 24.8,
    redZoneTargets: 18,
    overallRating: 87.5,
    isElite: false,
    note: "Veteran route runner who finds soft spots in zone",
  },
  {
    id: 11,
    name: "Mike Evans",
    team: "TB",
    position: "WR",
    manSeparation: 0.22,
    zoneSeparation: 0.17,
    catchRate: 62.1,
    yardsPerRoute: 2.2,
    targetShare: 22.3,
    redZoneTargets: 25,
    overallRating: 86.8,
    isElite: false,
    note: "Red zone specialist with size advantage",
  },
  {
    id: 12,
    name: "Cooper Kupp",
    team: "LAR",
    position: "WR",
    manSeparation: 0.26,
    zoneSeparation: 0.29,
    catchRate: 72.8,
    yardsPerRoute: 2.3,
    targetShare: 27.1,
    redZoneTargets: 20,
    overallRating: 88.2,
    isElite: false,
    note: "Excellent at finding space in zone coverage",
  },
  {
    id: 13,
    name: "DK Metcalf",
    team: "SEA",
    position: "WR",
    manSeparation: 0.27,
    zoneSeparation: 0.16,
    catchRate: 63.5,
    yardsPerRoute: 2.1,
    targetShare: 24.2,
    redZoneTargets: 21,
    overallRating: 86.4,
    isElite: false,
    note: "Physical specimen who wins with size and speed",
  },
  {
    id: 14,
    name: "Jaylen Waddle",
    team: "MIA",
    position: "WR",
    manSeparation: 0.32,
    zoneSeparation: 0.19,
    catchRate: 67.9,
    yardsPerRoute: 2.4,
    targetShare: 22.8,
    redZoneTargets: 12,
    overallRating: 87.1,
    isElite: false,
    note: "Speed threat who creates separation with quickness",
  },
  {
    id: 15,
    name: "Chris Olave",
    team: "NO",
    position: "WR",
    manSeparation: 0.24,
    zoneSeparation: 0.23,
    catchRate: 68.4,
    yardsPerRoute: 2.2,
    targetShare: 23.7,
    redZoneTargets: 15,
    overallRating: 85.9,
    isElite: false,
    note: "Smooth route runner with good deep ball tracking",
  },
  {
    id: 16,
    name: "Terry McLaurin",
    team: "WAS",
    position: "WR",
    manSeparation: 0.26,
    zoneSeparation: 0.18,
    catchRate: 64.7,
    yardsPerRoute: 2.0,
    targetShare: 24.5,
    redZoneTargets: 16,
    overallRating: 85.3,
    isElite: false,
    note: "Consistent producer despite quarterback inconsistency",
  },
  {
    id: 17,
    name: "Deebo Samuel",
    team: "SF",
    position: "WR",
    manSeparation: 0.23,
    zoneSeparation: 0.2,
    catchRate: 65.8,
    yardsPerRoute: 2.3,
    targetShare: 21.9,
    redZoneTargets: 14,
    overallRating: 85.7,
    isElite: false,
    note: "Versatile weapon who excels with ball in hands",
  },
  {
    id: 18,
    name: "Tee Higgins",
    team: "CIN",
    position: "WR",
    manSeparation: 0.25,
    zoneSeparation: 0.19,
    catchRate: 66.2,
    yardsPerRoute: 2.1,
    targetShare: 22.6,
    redZoneTargets: 17,
    overallRating: 85.1,
    isElite: false,
    note: "Big-bodied receiver with good contested catch ability",
  },
  {
    id: 19,
    name: "Calvin Ridley",
    team: "TEN",
    position: "WR",
    manSeparation: 0.27,
    zoneSeparation: 0.17,
    catchRate: 63.9,
    yardsPerRoute: 2.0,
    targetShare: 23.1,
    redZoneTargets: 13,
    overallRating: 84.8,
    isElite: false,
    note: "Precise route runner returning to form",
  },
  {
    id: 20,
    name: "Michael Pittman Jr.",
    team: "IND",
    position: "WR",
    manSeparation: 0.21,
    zoneSeparation: 0.22,
    catchRate: 67.5,
    yardsPerRoute: 1.9,
    targetShare: 25.2,
    redZoneTargets: 19,
    overallRating: 84.5,
    isElite: false,
    note: "Reliable possession receiver with good hands",
  },

  // Quarterbacks (QB) with real data
  {
    id: 101,
    name: "Patrick Mahomes",
    team: "KC",
    position: "QB",
    avgDepthOfTarget: 7.0,
    shortCompletionPct: 81.4,
    intermediateCompletionPct: 65.1,
    longCompletionPct: 31.5,
    rushYardsPerAttempt: 5.29,
    rushTdPct: 3.45,
    overallRating: 96.5,
    isElite: true,
    note: "Elite quarterback with exceptional arm talent and improvisation skills",
  },
  {
    id: 102,
    name: "Josh Allen",
    team: "BUF",
    position: "QB",
    avgDepthOfTarget: 8.7,
    shortCompletionPct: 84.2,
    intermediateCompletionPct: 56.1,
    longCompletionPct: 43.7,
    rushYardsPerAttempt: 5.21,
    rushTdPct: 11.76,
    overallRating: 94.8,
    isElite: true,
    note: "Dual-threat quarterback with a powerful arm and excellent rushing ability",
  },
  {
    id: 103,
    name: "Joe Burrow",
    team: "CIN",
    position: "QB",
    avgDepthOfTarget: 7.7,
    shortCompletionPct: 87.3,
    intermediateCompletionPct: 65.5,
    longCompletionPct: 43.6,
    rushYardsPerAttempt: 4.79,
    rushTdPct: 4.76,
    overallRating: 93.2,
    isElite: true,
    note: "Accurate passer with excellent decision-making and pocket presence",
  },
  {
    id: 104,
    name: "Lamar Jackson",
    team: "BAL",
    position: "QB",
    avgDepthOfTarget: 9.3,
    shortCompletionPct: 83.2,
    intermediateCompletionPct: 76.4,
    longCompletionPct: 43.8,
    rushYardsPerAttempt: 6.58,
    rushTdPct: 2.88,
    overallRating: 92.5,
    isElite: true,
    note: "Dynamic runner with improving passing skills and exceptional athleticism",
  },
  {
    id: 105,
    name: "Justin Herbert",
    team: "LAC",
    position: "QB",
    avgDepthOfTarget: 9.2,
    shortCompletionPct: 84.8,
    intermediateCompletionPct: 68.5,
    longCompletionPct: 44.0,
    rushYardsPerAttempt: 4.43,
    rushTdPct: 2.9,
    overallRating: 91.8,
    isElite: true,
    note: "Strong-armed quarterback with excellent pocket presence and accuracy",
  },
  {
    id: 106,
    name: "Dak Prescott",
    team: "DAL",
    position: "QB",
    avgDepthOfTarget: 8.3,
    shortCompletionPct: 78.4,
    intermediateCompletionPct: 53.8,
    longCompletionPct: 50.0,
    rushYardsPerAttempt: 4.15,
    rushTdPct: 7.69,
    overallRating: 90.6,
    isElite: true,
    note: "Well-rounded quarterback with good decision-making and leadership",
  },
  {
    id: 107,
    name: "Jalen Hurts",
    team: "PHI",
    position: "QB",
    avgDepthOfTarget: 8.1,
    shortCompletionPct: 88.3,
    intermediateCompletionPct: 69.9,
    longCompletionPct: 48.0,
    rushYardsPerAttempt: 4.2,
    rushTdPct: 9.33,
    overallRating: 89.8,
    isElite: false,
    note: "Dual-threat quarterback with excellent rushing ability in the red zone",
  },
  {
    id: 108,
    name: "Aaron Rodgers",
    team: "NYJ",
    position: "QB",
    avgDepthOfTarget: 7.3,
    shortCompletionPct: 82.2,
    intermediateCompletionPct: 50.5,
    longCompletionPct: 42.9,
    rushYardsPerAttempt: 4.86,
    rushTdPct: 0.0,
    overallRating: 89.5,
    isElite: false,
    note: "Veteran quarterback with exceptional accuracy and decision-making",
  },
  {
    id: 109,
    name: "Tua Tagovailoa",
    team: "MIA",
    position: "QB",
    avgDepthOfTarget: 6.1,
    shortCompletionPct: 87.1,
    intermediateCompletionPct: 61.1,
    longCompletionPct: 37.5,
    rushYardsPerAttempt: 2.88,
    rushTdPct: 0.0,
    overallRating: 88.7,
    isElite: false,
    note: "Accurate passer who excels in a timing-based offense",
  },
  {
    id: 110,
    name: "Matthew Stafford",
    team: "LAR",
    position: "QB",
    avgDepthOfTarget: 8.3,
    shortCompletionPct: 80.4,
    intermediateCompletionPct: 59.3,
    longCompletionPct: 43.1,
    rushYardsPerAttempt: 1.37,
    rushTdPct: 0.0,
    overallRating: 88.2,
    isElite: false,
    note: "Strong-armed quarterback with excellent deep ball accuracy",
  },
  {
    id: 111,
    name: "Kirk Cousins",
    team: "ATL",
    position: "QB",
    avgDepthOfTarget: 8.0,
    shortCompletionPct: 83.7,
    intermediateCompletionPct: 60.5,
    longCompletionPct: 50.0,
    rushYardsPerAttempt: 0.0,
    rushTdPct: 0.0,
    overallRating: 87.9,
    isElite: false,
    note: "Accurate passer who excels in play-action and structured offenses",
  },
  {
    id: 112,
    name: "Trevor Lawrence",
    team: "JAX",
    position: "QB",
    avgDepthOfTarget: 9.9,
    shortCompletionPct: 80.3,
    intermediateCompletionPct: 51.5,
    longCompletionPct: 50.0,
    rushYardsPerAttempt: 4.58,
    rushTdPct: 11.54,
    overallRating: 87.5,
    isElite: false,
    note: "Young quarterback with excellent physical tools and developing consistency",
  },
  {
    id: 113,
    name: "Jared Goff",
    team: "DET",
    position: "QB",
    avgDepthOfTarget: 7.2,
    shortCompletionPct: 87.1,
    intermediateCompletionPct: 65.6,
    longCompletionPct: 41.7,
    rushYardsPerAttempt: 1.6,
    rushTdPct: 0.0,
    overallRating: 86.8,
    isElite: false,
    note: "Pocket passer who excels in a structured offense with good protection",
  },
  {
    id: 114,
    name: "Brock Purdy",
    team: "SF",
    position: "QB",
    avgDepthOfTarget: 9.0,
    shortCompletionPct: 80.1,
    intermediateCompletionPct: 67.7,
    longCompletionPct: 46.9,
    rushYardsPerAttempt: 4.89,
    rushTdPct: 7.58,
    overallRating: 86.5,
    isElite: false,
    note: "Efficient quarterback who excels in a system with strong supporting cast",
  },
  {
    id: 115,
    name: "Deshaun Watson",
    team: "CLE",
    position: "QB",
    avgDepthOfTarget: 7.1,
    shortCompletionPct: 79.0,
    intermediateCompletionPct: 72.2,
    longCompletionPct: 26.3,
    rushYardsPerAttempt: 4.77,
    rushTdPct: 3.23,
    overallRating: 86.2,
    isElite: false,
    note: "Athletic quarterback with good arm talent working to regain form",
  },
  {
    id: 116,
    name: "Russell Wilson",
    team: "PIT",
    position: "QB",
    avgDepthOfTarget: 8.4,
    shortCompletionPct: 85.9,
    intermediateCompletionPct: 68.1,
    longCompletionPct: 56.0,
    rushYardsPerAttempt: 3.6,
    rushTdPct: 4.65,
    overallRating: 85.8,
    isElite: false,
    note: "Veteran quarterback known for deep ball accuracy and escapability",
  },
  {
    id: 117,
    name: "Kyler Murray",
    team: "ARI",
    position: "QB",
    avgDepthOfTarget: 7.4,
    shortCompletionPct: 85.2,
    intermediateCompletionPct: 59.6,
    longCompletionPct: 34.5,
    rushYardsPerAttempt: 7.33,
    rushTdPct: 6.41,
    overallRating: 85.5,
    isElite: false,
    note: "Dynamic athlete with quick release and excellent scrambling ability",
  },
  {
    id: 118,
    name: "Derek Carr",
    team: "NO",
    position: "QB",
    avgDepthOfTarget: 8.6,
    shortCompletionPct: 86.3,
    intermediateCompletionPct: 71.4,
    longCompletionPct: 43.6,
    rushYardsPerAttempt: 4.18,
    rushTdPct: 5.88,
    overallRating: 84.9,
    isElite: false,
    note: "Accurate passer who performs well from clean pockets",
  },
  {
    id: 119,
    name: "Geno Smith",
    team: "SEA",
    position: "QB",
    avgDepthOfTarget: 7.6,
    shortCompletionPct: 85.6,
    intermediateCompletionPct: 62.6,
    longCompletionPct: 49.2,
    rushYardsPerAttempt: 5.13,
    rushTdPct: 3.77,
    overallRating: 84.6,
    isElite: false,
    note: "Resurgent quarterback with good accuracy and decision-making",
  },
  {
    id: 120,
    name: "Baker Mayfield",
    team: "TB",
    position: "QB",
    avgDepthOfTarget: 7.4,
    shortCompletionPct: 86.3,
    intermediateCompletionPct: 67.8,
    longCompletionPct: 44.2,
    rushYardsPerAttempt: 6.3,
    rushTdPct: 5.0,
    overallRating: 84.2,
    isElite: false,
    note: "Competitive quarterback with good arm strength and improving consistency",
  },
  {
    id: 121,
    name: "C.J. Stroud",
    team: "HOU",
    position: "QB",
    avgDepthOfTarget: 8.8,
    shortCompletionPct: 76.4,
    intermediateCompletionPct: 66.0,
    longCompletionPct: 41.4,
    rushYardsPerAttempt: 4.48,
    rushTdPct: 0.0,
    overallRating: 83.8,
    isElite: false,
    note: "Young quarterback with excellent processing and accuracy",
  },
  {
    id: 122,
    name: "Justin Fields",
    team: "PIT",
    position: "QB",
    avgDepthOfTarget: 7.8,
    shortCompletionPct: 88.5,
    intermediateCompletionPct: 63.6,
    longCompletionPct: 36.8,
    rushYardsPerAttempt: 4.66,
    rushTdPct: 8.06,
    overallRating: 83.5,
    isElite: false,
    note: "Athletic quarterback with elite rushing ability and developing passing skills",
  },
  {
    id: 123,
    name: "Sam Darnold",
    team: "MIN",
    position: "QB",
    avgDepthOfTarget: 9.3,
    shortCompletionPct: 88.1,
    intermediateCompletionPct: 61.5,
    longCompletionPct: 50.7,
    rushYardsPerAttempt: 3.16,
    rushTdPct: 1.49,
    overallRating: 82.8,
    isElite: false,
    note: "Mobile quarterback with good arm talent seeking consistency",
  },
  {
    id: 124,
    name: "Daniel Jones",
    team: "NYG",
    position: "QB",
    avgDepthOfTarget: 7.5,
    shortCompletionPct: 84.8,
    intermediateCompletionPct: 68.8,
    longCompletionPct: 32.3,
    rushYardsPerAttempt: 3.96,
    rushTdPct: 2.99,
    overallRating: 82.5,
    isElite: false,
    note: "Athletic quarterback with good rushing ability but inconsistent passing",
  },
  {
    id: 125,
    name: "Bryce Young",
    team: "CAR",
    position: "QB",
    avgDepthOfTarget: 9.0,
    shortCompletionPct: 80.8,
    intermediateCompletionPct: 58.5,
    longCompletionPct: 50.9,
    rushYardsPerAttempt: 5.79,
    rushTdPct: 13.95,
    overallRating: 82.2,
    isElite: false,
    note: "Young quarterback with good processing and accuracy developing at the NFL level",
  },
  {
    id: 126,
    name: "Caleb Williams",
    team: "CHI",
    position: "QB",
    avgDepthOfTarget: 8.1,
    shortCompletionPct: 87.0,
    intermediateCompletionPct: 54.5,
    longCompletionPct: 28.0,
    rushYardsPerAttempt: 6.04,
    rushTdPct: 0.0,
    overallRating: 81.8,
    isElite: false,
    note: "Rookie quarterback with excellent arm talent and playmaking ability",
  },
  {
    id: 127,
    name: "Jayden Daniels",
    team: "WAS",
    position: "QB",
    avgDepthOfTarget: 7.7,
    shortCompletionPct: 80.7,
    intermediateCompletionPct: 75.2,
    longCompletionPct: 38.6,
    rushYardsPerAttempt: 6.02,
    rushTdPct: 4.05,
    overallRating: 81.5,
    isElite: false,
    note: "Rookie quarterback with excellent mobility and developing passing skills",
  },
  {
    id: 128,
    name: "Bo Nix",
    team: "DEN",
    position: "QB",
    avgDepthOfTarget: 7.9,
    shortCompletionPct: 83.3,
    intermediateCompletionPct: 60.0,
    longCompletionPct: 46.8,
    rushYardsPerAttempt: 4.67,
    rushTdPct: 4.35,
    overallRating: 81.2,
    isElite: false,
    note: "Rookie quarterback with good mobility and quick decision-making",
  },
  {
    id: 129,
    name: "Will Levis",
    team: "TEN",
    position: "QB",
    avgDepthOfTarget: 9.1,
    shortCompletionPct: 78.3,
    intermediateCompletionPct: 60.9,
    longCompletionPct: 44.7,
    rushYardsPerAttempt: 4.07,
    rushTdPct: 0.0,
    overallRating: 80.8,
    isElite: false,
    note: "Young quarterback with strong arm and developing consistency",
  },
  {
    id: 131,
    name: "Jordan Love",
    team: "GB",
    position: "QB",
    avgDepthOfTarget: 9.2,
    shortCompletionPct: 85.7,
    intermediateCompletionPct: 62.2,
    longCompletionPct: 40.5,
    rushYardsPerAttempt: 3.32,
    rushTdPct: 4.0,
    overallRating: 85.0,
    isElite: false,
    note: "Developing quarterback with good arm talent and mobility",
  },
  {
    id: 132,
    name: "Drake Maye",
    team: "NE",
    position: "QB",
    avgDepthOfTarget: 7.4,
    shortCompletionPct: 81.6,
    intermediateCompletionPct: 54.2,
    longCompletionPct: 36.7,
    rushYardsPerAttempt: 7.8,
    rushTdPct: 3.7,
    overallRating: 81.0,
    isElite: false,
    note: "Rookie quarterback with good arm strength and mobility",
  },
  {
    id: 133,
    name: "Mac Jones",
    team: "JAX",
    position: "QB",
    avgDepthOfTarget: 7.7,
    shortCompletionPct: 86.7,
    intermediateCompletionPct: 51.9,
    longCompletionPct: 19.2,
    rushYardsPerAttempt: 3.29,
    rushTdPct: 3.57,
    overallRating: 79.5,
    isElite: false,
    note: "Pocket passer with good short-area accuracy",
  },
  {
    id: 134,
    name: "Gardner Minshew",
    team: "LV",
    position: "QB",
    avgDepthOfTarget: 6.2,
    shortCompletionPct: 81.5,
    intermediateCompletionPct: 60.0,
    longCompletionPct: 40.9,
    rushYardsPerAttempt: 3.05,
    rushTdPct: 0.0,
    overallRating: 79.0,
    isElite: false,
    note: "Backup quarterback with good decision-making and mobility",
  },
  {
    id: 135,
    name: "Joe Flacco",
    team: "IND",
    position: "QB",
    avgDepthOfTarget: 9.2,
    shortCompletionPct: 81.5,
    intermediateCompletionPct: 66.0,
    longCompletionPct: 41.2,
    rushYardsPerAttempt: 2.89,
    rushTdPct: 0.0,
    overallRating: 78.5,
    isElite: false,
    note: "Veteran quarterback with strong arm and playoff experience",
  },
  {
    id: 136,
    name: "Spencer Rattler",
    team: "NO",
    position: "QB",
    avgDepthOfTarget: 8.2,
    shortCompletionPct: 80.0,
    intermediateCompletionPct: 61.4,
    longCompletionPct: 19.2,
    rushYardsPerAttempt: 8.11,
    rushTdPct: 0.0,
    overallRating: 77.0,
    isElite: false,
    note: "Rookie quarterback with good arm talent and developing decision-making",
  },
  {
    id: 137,
    name: "Aidan O'Connell",
    team: "LV",
    position: "QB",
    avgDepthOfTarget: 8.3,
    shortCompletionPct: 79.8,
    intermediateCompletionPct: 52.9,
    longCompletionPct: 40.0,
    rushYardsPerAttempt: 1.43,
    rushTdPct: 4.76,
    overallRating: 76.5,
    isElite: false,
    note: "Young pocket passer with developing accuracy and field vision",
  },
  {
    id: 138,
    name: "Mason Rudolph",
    team: "TEN",
    position: "QB",
    avgDepthOfTarget: 7.6,
    shortCompletionPct: 85.7,
    intermediateCompletionPct: 62.7,
    longCompletionPct: 50.0,
    rushYardsPerAttempt: 4.24,
    rushTdPct: 4.0,
    overallRating: 76.0,
    isElite: false,
    note: "Backup quarterback with good arm strength and developing consistency",
  },
  {
    id: 139,
    name: "Drew Lock",
    team: "NYG",
    position: "QB",
    avgDepthOfTarget: 7.3,
    shortCompletionPct: 86.8,
    intermediateCompletionPct: 50.0,
    longCompletionPct: 21.7,
    rushYardsPerAttempt: 7.39,
    rushTdPct: 11.11,
    overallRating: 75.5,
    isElite: false,
    note: "Athletic quarterback with good arm strength but inconsistent accuracy",
  },
  {
    id: 140,
    name: "Jacoby Brissett",
    team: "NE",
    position: "QB",
    avgDepthOfTarget: 7.3,
    shortCompletionPct: 78.9,
    intermediateCompletionPct: 50.0,
    longCompletionPct: 22.2,
    rushYardsPerAttempt: 4.13,
    rushTdPct: 0.0,
    overallRating: 75.0,
    isElite: false,
    note: "Veteran backup with good mobility and leadership",
  },
  {
    id: 141,
    name: "Andy Dalton",
    team: "CAR",
    position: "QB",
    avgDepthOfTarget: 7.0,
    shortCompletionPct: 82.9,
    intermediateCompletionPct: 63.3,
    longCompletionPct: 57.1,
    rushYardsPerAttempt: 3.09,
    rushTdPct: 0.0,
    overallRating: 74.5,
    isElite: false,
    note: "Veteran quarterback with good accuracy and experience",
  },
  {
    id: 142,
    name: "Tyler Huntley",
    team: "BAL",
    position: "QB",
    avgDepthOfTarget: 8.2,
    shortCompletionPct: 82.7,
    intermediateCompletionPct: 82.4,
    longCompletionPct: 8.3,
    rushYardsPerAttempt: 5.19,
    rushTdPct: 7.69,
    overallRating: 74.0,
    isElite: false,
    note: "Athletic backup with good mobility and developing passing skills",
  },
  {
    id: 143,
    name: "Dorian Thompson-Robinson",
    team: "CLE",
    position: "QB",
    avgDepthOfTarget: 5.7,
    shortCompletionPct: 68.9,
    intermediateCompletionPct: 57.1,
    longCompletionPct: 0.0,
    rushYardsPerAttempt: 5.81,
    rushTdPct: 0.0,
    overallRating: 73.5,
    isElite: false,
    note: "Rookie quarterback with good athleticism and developing passing skills",
  },
  {
    id: 144,
    name: "Michael Penix Jr.",
    team: "ATL",
    position: "QB",
    avgDepthOfTarget: 10.6,
    shortCompletionPct: 87.5,
    intermediateCompletionPct: 54.8,
    longCompletionPct: 43.8,
    rushYardsPerAttempt: 1.57,
    rushTdPct: 14.29,
    overallRating: 73.0,
    isElite: false,
    note: "Rookie quarterback with excellent arm talent and deep ball accuracy",
  },
  {
    id: 145,
    name: "Desmond Ridder",
    team: "ARI",
    position: "QB",
    avgDepthOfTarget: 7.9,
    shortCompletionPct: 82.6,
    intermediateCompletionPct: 60.0,
    longCompletionPct: 20.0,
    rushYardsPerAttempt: 4.0,
    rushTdPct: 0.0,
    overallRating: 72.5,
    isElite: false,
    note: "Young quarterback with good mobility and developing passing skills",
  },
  {
    id: 146,
    name: "Malik Willis",
    team: "GB",
    position: "QB",
    avgDepthOfTarget: 7.5,
    shortCompletionPct: 89.5,
    intermediateCompletionPct: 70.0,
    longCompletionPct: 75.0,
    rushYardsPerAttempt: 6.9,
    rushTdPct: 5.0,
    overallRating: 72.0,
    isElite: false,
    note: "Athletic quarterback with excellent rushing ability and developing passing skills",
  },
  {
    id: 147,
    name: "Tim Boyle",
    team: "DEN",
    position: "QB",
    avgDepthOfTarget: 7.7,
    shortCompletionPct: 56.5,
    intermediateCompletionPct: 50.0,
    longCompletionPct: 60.0,
    rushYardsPerAttempt: 3.0,
    rushTdPct: 0.0,
    overallRating: 71.5,
    isElite: false,
    note: "Backup quarterback with good arm strength but inconsistent accuracy",
  },
  {
    id: 148,
    name: "Jameis Winston",
    team: "CLE",
    position: "QB",
    avgDepthOfTarget: 9.7,
    shortCompletionPct: 82.6,
    intermediateCompletionPct: 63.0,
    longCompletionPct: 37.1,
    rushYardsPerAttempt: 3.32,
    rushTdPct: 4.0,
    overallRating: 71.0,
    isElite: false,
    note: "Veteran quarterback with strong arm and aggressive downfield mentality",
  },
  {
    id: 149,
    name: "Cooper Rush",
    team: "DAL",
    position: "QB",
    avgDepthOfTarget: 7.5,
    shortCompletionPct: 76.7,
    intermediateCompletionPct: 56.9,
    longCompletionPct: 35.5,
    rushYardsPerAttempt: 0.69,
    rushTdPct: 0.0,
    overallRating: 70.5,
    isElite: false,
    note: "Backup quarterback with good system knowledge and decision-making",
  },
]

// You can add more players for each position to have a larger dataset

